platform: &platform
    platform: android

device_config: &device_config
    ios:
        platformName: 'ios'
        platformVersion: '13.5'
        deviceName: 'iPhone 11 Pro MT'
        automationName: 'XCUITest'
        appPackage: ''
        appActivity: ''
        noReset: 'True'
        folder: 'Apps/app.app'
    android:
        platformName: 'Android'
        platformVersion: ''
        deviceName: 'Android'
        automationName: 'uiautomator2'
        appPackage: 'appPackage'
        appActivity: 'appActivity'
        noReset: 'True'
        folder: 'Apps/app.apk'

production:
    <<: *platform
    <<: *device_config